# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/maretol/dashoot
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...


  document:
    docker:
      - image: circleci/openjdk:9.0.4
    working_directory: ~/doc
    steps:
      - checkout
      # 以下WSDファイルの変換
      - run: java -jar ./plantuml.jar *.wsd
      - run: git checkout -b auto-document
      - run: git add ~/*
      - run: git commit -am "auto commit"
      - run: git push origin auto-document

workflows:
  version: 2
  create_document:
    triggers:
      schedule:
        filters:
          branches:
            only:
              - document
    jobs:
      - document
